version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:17.0
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
    ports:
      - '${PG_PORT}:5432'
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - .env
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
