version: '3.8'

services:
  app:
    build:
      context: .
    container_name: auth
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_SECRET_REFRESH=${JWT_SECRET_REFRESH}
      - JWT_TOKEN_EXPIRES_IN=${JWT_TOKEN_EXPIRES_IN}
      - JWT_REFRESH_TOKEN_EXPIRES_IN=${JWT_REFRESH_TOKEN_EXPIRES_IN}
      - USER_EXPIRES_PROVISIONAL_PASSWORD_IN_MINUTES=${USER_EXPIRES_PROVISIONAL_PASSWORD_IN_MINUTES}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_SECURE=${MAIL_SECURE}
      - MAIL_DEFAULT_SENDER=${MAIL_DEFAULT_SENDER}
      - MAIL_PASS=${MAIL_PASS}
      - MAIL_APP_NAME=${MAIL_APP_NAME}
      - MAIL_REDIRECT=${MAIL_REDIRECT}
      - MAIL_HEADER_IMAGE=${MAIL_HEADER_IMAGE}
      - DATABASE_URL=${DATABASE_URL}
      - RABBITMQ_EXCHANGE_EXPIRED_MSGS=${RABBITMQ_EXCHANGE_EXPIRED_MSGS}
      - RABBITMQ_TTL_MSGS=${RABBITMQ_TTL_MSGS}
      - RABBITMQ_EXCHANGE_NAME=${RABBITMQ_EXCHANGE_NAME}
      - RABBITMQ_EXCHANGE_TYPE=${RABBITMQ_EXCHANGE_TYPE}
      - RABBITMQ_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@${RABBITMQ_HOST}:${RABBITMQ_PORT}/${RABBITMQ_VIRTUAL_HOST}
    ports:
      - '127.0.0.1:${APP_PORT}:3000'
    env_file:
      - .env
    restart: always
