version: '3.8'

services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: auth
  #   environment:
  #     - JWT_SECRET=${JWT_SECRET}
  #     - JWT_SECRET_REFRESH=${JWT_SECRET_REFRESH}
  #     - JWT_TOKEN_EXPIRES_IN=${JWT_TOKEN_EXPIRES_IN}
  #     - JWT_REFRESH_TOKEN_EXPIRES_IN=${JWT_REFRESH_TOKEN_EXPIRES_IN}
  #     - USER_EXPIRES_PROVISIONAL_PASSWORD_IN_MINUTES=${USER_EXPIRES_PROVISIONAL_PASSWORD_IN_MINUTES}
  #     - MAIL_HOST=${MAIL_HOST}
  #     - MAIL_PORT=${MAIL_PORT}
  #     - MAIL_SECURE=${MAIL_SECURE}
  #     - MAIL_DEFAULT_SENDER=${MAIL_DEFAULT_SENDER}
  #     - MAIL_PASS=${MAIL_PASS}
  #     - MAIL_APP_NAME=${MAIL_APP_NAME}
  #     - MAIL_REDIRECT=${MAIL_REDIRECT}
  #     - MAIL_HEADER_IMAGE=${MAIL_HEADER_IMAGE}
  #     - DATABASE_URL=${DATABASE_URL}
  #   ports:
  #     - '${APP_PORT}:3000'
  #   depends_on:
  #     - postgres
  #   env_file:
  #     - .env
  #   networks:
  #     - app_auth_network

  postgres:
    container_name: postgres
    image: postgres:17.0
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
    ports:
      - '${PG_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - app_auth_network

  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   networks:
  #     - app_auth_network
  #   restart: always

volumes:
  postgres_data:
    driver: local

networks:
  app_auth_network:
    driver: bridge
